### ISSUE TITLE
Adjusting Table Columns Causes Them to Misalign

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/ego-ui#143] opened 2021-03-19 12:51 UTC
Adjusting any of the table columns in Ego-UI causes the columns to misalign and display improperly

Example:
![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/0c2b0577-4dca-49e8-83e6-3663d004a2db)

**Comment by anncatton** [comment] 2021-05-04 17:19
I think this is a duplicate of #96

**Comment by rosibaj** [comment] 2021-05-14 18:54
Closing as a duplicate.

**Closed by rosibaj** 2021-05-14 18:54 UTC
Labels: canarie, enhancement
